### ISSUE TITLE
Cross-platform compability (Windows / Mac / Linux)

### ISSUE THREAD

**Issue by matsest** [StefanIvemo/BicepPowerShell#116]
**Describe the bug**
General bug to discuss how the module should deal with cross-platform compability. (I'm assuming that this module aims at being as compatible across platforms as Bicep is - correct me if I'm wrong).

I'm a multi-platform user of Powershell, Bicep/ARM and really like this module! Great work!

In terms of [cross-platform compability](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_editions?view=powershell-7.1#authoring-powershell-modules-for-edition-cross-compatibility) (Powershell 7.x for Windows, Linux and Mac) there are a few small bugs that is easy to fix (examples: #115 #107).

However, there are some cmdlet's that are not so easily cross compatible:

- Install-BicepCLI
- Uninstall-BicepCLI
- Update-BicepCLI

In terms of what value this module adds, I (personally) don't think managing installation of Bicep on all platforms is something to aim for<sup>[1](#myfootnote1)</sup>. But this module supports automated installation of Bicep with Powershell on Windows, which MS doesn't currently offer.

So my suggestion is, instead of casting exception errors like this when trying to run X-BicepCLI commands on Linux/Mac:

```powershell
> Uninstall-BicepCLI
MethodInvocationException:
Line |
   9 |          $currentPrincipal = New-Object Security.Principal.WindowsPrin …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetCurrent" with "0" argument(s): "Windows Principal functionality is not supported on this platform."
InvalidOperation:
Line |
  10 |          $IsAdmin = $currentPrincipal.IsInRole([Security.Principal.Win …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
Uninstall-BicepCLI: Some Bicep parts might not be properly uninstalled unless you run elevated. Use the -Force switch to try anyway. Any Bicep version installed by Azure CLI to %USERPROFILE%\.Azure\bin will not be uninstalled.
```
I think it could be a good start to add some checks for OS on these cmdlets (at least as a start). And perhaps mention that in the docs for these cmdlets as well.

A simple suggestion is to in the start of each cmdlet add blocks like this, (or optionally investigate if these cmdlets need a more thorough check for Windows-specific-compability)

```powershell
    if (!($PSVersionTable.Platform -like "Win32NT")) {
        Write-Error -Message "This cmdlet is only supported for Windows systems. `
To [install/uninstall/update] Bicep on your system see instructions on https://github.com/Azure/bicep"
        break
    }
```

Idk, let me know what you think. Thanks again for an awesome module!

<a name="myfootnote1">1</a>:  As cross platform Bicep install/upgrade/uninstall is already covered by [az cli and soon(?) Azure Powershell](https://github.com/Azure/bicep/blob/main/docs/installing.md#install-and-manage-via-azure-cli-easiest)

**Comment by bjompen** [comment]
I agree that adding checks for plattform is a good thing to add.
The easiest way to get started would be to simply wrap commands that are specific in $IsWindows, $IsLinux, and $IsMacOS (we also have the magic variable $IsCoreCLR if we need to verify .Net Core)

If we add issues where we find problems we can easily track compatibility status as well (X isnt tested on y)

As for the specific example, Install-BicepCLI we should probably have a separate discussion weather it is necessary to add support for other plattforms as well.

**Comment by SimonWahlin** [comment]
I fully support adding some checks for non-windows OS and error out gracefully like @matsest suggests.

Having full cross platform support would of course be nice, but nice errors is a good start.

**Comment by StefanIvemo** [comment]
I can even consider scrapping these commands. As @matsest mentions we already have support for all those features in Azure CLI and it's in the works for Azure PowerShell. Any user authoring Bicep templates will have one of those tools. After we stopped wrapping the CLI we've kept them because there was no support for easy install/upgrade/uninstall of the CLI. Might be time to say good bye 🙂.

**Comment by StefanIvemo** [comment]
It's worth to mention though that `az bicep install` only downloads Bicep CLI to use with Azure CLI. It stores it in `%USERPROFILE%\.Azure\bin` on Windows and never registers the path, which makes it separate from any other installed version of Bicep CLI.

**Comment by StefanIvemo** [comment]
So where should we start? Just by adding $IsWindows, $IsLinux, and $IsMacOS checks to the functions and inform the user that they only work for Windows users at the moment?

**Comment by matsest** [comment]
I think that's a fairly straightforward task :) Depends on what style you like, but I think something like

```powershell
    ....cmdlet params
    if (!($IsWindows)) {
        Write-Error -Message "This cmdlet is only supported for Windows systems. `
To [install/uninstall/update] Bicep on your system see instructions on https://github.com/Azure/bicep"
        break
    }
    ....cmdlet body
```

or

```powershell
    ....cmdlet params
    if (!($IsWindows)) {
        Write-Error -Message "This cmdlet is only supported for Windows systems. `
To [install/uninstall/update] Bicep on your system see instructions on https://github.com/Azure/bicep"
    } else {
    ....cmdlet body
    }
```

should do. Beside this check, the check for Powershell version is done by module import, and the assemblies is already defined there as well, so for general install/use of the module that should be sufficient.

What do you think?

**Comment by PalmEmanuel** [comment]
Since we only need to handle two cases for now, i.e. Windows or not, I like the "if else" format of your second suggestion, but both are fine 👍

**Comment by StefanIvemo** [comment]
Agree with @PalmEmanuel that both looks good, your choice 🙂.
