### ISSUE TITLE
Update tests to work with Pester 5.2.0

### ISSUE THREAD

**Issue by emilguden** [StefanIvemo/BicepPowerShell#137]
**Describe the bug**
The Pester tests fails when using the latest version of the PowerShell module which is 5.2.0

**To Reproduce**
1. Run a PR without the -RequiredVersion 5.1.1 in the .\.github\workflows\RunTests.yaml file, row 23.

**Expected behavior**
Run Write-Host 'Invoking Pester'
Invoking Pester

Starting discovery in 6 files.
Discovery finished in 837ms.
Running tests.
[+] D:\a\BicepPowerShell\BicepPowerShell\Tests\CompareBicepVersion.Tests.ps1 1.93s (535ms|698ms)
[+] D:\a\BicepPowerShell\BicepPowerShell\Tests\Install-BicepBuild.Tests.ps1 200ms (6ms|187ms)
[+] D:\a\BicepPowerShell\BicepPowerShell\Tests\InstalledBicepVersion.Tests.ps1 236ms (51ms|172ms)
[+] D:\a\BicepPowerShell\BicepPowerShell\Tests\ListBicepVersions.Tests.ps1 398ms (196ms|190ms)
[+] D:\a\BicepPowerShell\BicepPowerShell\Tests\Module.tests.ps1 898ms (543ms|282ms)
[-] TestBicep.Bicep CLI installed.Returns true when Bicep CLI is installed 103ms (100ms|2ms)
 Expected $true, but got $false.
 at TestBicep | Should -Be $true, D:\a\BicepPowerShell\BicepPowerShell\Tests\TestBicep.Tests.ps1:21
 at <ScriptBlock>, D:\a\BicepPowerShell\BicepPowerShell\Tests\TestBicep.Tests.ps1:21
Tests completed in 4.18s
Tests Passed: 30, Failed: 1, Skipped: 0 NotRun: 0
Error: Process completed with exit code 1.

**Additional context**

**Comment by StefanIvemo** [comment]
A work around for this bug has been implemented in #138. To fix the issue we need to update the tests to work with Pester 5.2.0.
