### ISSUE TITLE
Update module to work with the latest bicep release v0.3.539

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#147]
**Is your feature request related to a problem? Please describe.**
When updating the assemblies to the latest bicep release it throws an error on build and decompile.

```powershell
build-bicep -Path C:\git\StefanIvemo\vwan-playground\playground\VirtualWAN.bicep

MethodException: 
Line |
  12 |          $ResourceTypeProvider = [Bicep.Core.TypeSystem.Az.AzResourceT …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find an overload for "new" and the argument count: "0".
MethodInvocationException:
Line |
  15 |          $CompilationResults = $Compilation.GetAllDiagnosticsBySyntaxT …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetAllDiagnosticsBySyntaxTree" with "0" argument(s): "Object reference not set to an instance of an object."
MethodInvocationException:
Line |
  50 |              $EmitResult = $Emitter.Emit($Stream)
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Emit" with "1" argument(s): "Object reference not set to an instance of an object."
```

**Describe the solution you'd like**
It seems like the issue is related to additional functionality in `Bicep.Core.TypeSystem.Az.AzResourceTypeProvider`.

If I change:
`$ResourceTypeProvider = [Bicep.Core.TypeSystem.Az.AzResourceTypeProvider]::new()`

To:
`$ResourceTypeProvider = [Bicep.Core.TypeSystem.Az.AzResourceTypeProvider]::CreateWithAzTypes()`

I get it to work as expected. But I'm not sure if it will always be the `CreateWithAzTypes` method that should be used or not. 

Can someone with more experience with with .Net take a look and see if this is a valid fix?

**Comment by SimonWahlin** [comment]
Yes we should use CreateWithAzTypes() since that's what bicep.exe seems to be doing.

Reference: [Program.cs Line 42](https://github.com/Azure/bicep/blob/c8b397dbdd8cb027948c6c146f221d653db566f3/src/Bicep.Cli/Program.cs#L42)
