### ISSUE TITLE
New command Test-BicepFile

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#171]
**Is your feature request related to a problem? Please describe.**
Now that we don't build our bicep files before deployment we need a command to test the bicep file. It should basically do a build without outputting the file.

**Describe the solution you'd like**
I want to be able to do something like this:

```powershell
Test-BicepFile -Path c:\myBiceps\vnet.bicep
``` 
It should output all build and linter warnings and errors. And preferably separate the linter and build warnings to make it readable. Today the output is quite messy.

**A crappy bicep to test with:**
```bicep

param unused string

@secure()
param adminPassword string = 'HardcodedPassword'
param suffix string = '001'

var nsgName = concat('nsg-', suffix)
var AzureURL = 'https://management.azure.com'
var AzureSchemaURL1 = concat('https://','gallery.azure.com')
var unusedString = 'string'

resource nsg1 'Microsoft.Network/networkSecurityGroups@2021-11-01' = {
  name: '${nsgName}'
  location: resourceGroup().location
  properties: {
    
  }
}

resource nsg2 'Microsoft.Network/networkSecurityGroups@2021-11-01' = {
  name: '${nsgName}'
  location: resourceGroup().location
  properties: {
    
  }
}

output string array = 'string'

```

**Additional context**

**Comment by PalmEmanuel** [comment]
Together with this functionality we may want to rename the private function TestBicep to TestBicepCLI, to avoid any potential confusion.
