### ISSUE TITLE
ConvertTo-Bicep defaults to overwriting existing files.

### ISSUE THREAD

**Issue by bjompen** [StefanIvemo/BicepPowerShell#187]
The default behaviour of the bicep cli when running `bicep decompile template.json` is to overwrote already existing .bicep files in the current folder, and as so, for parity, running `ConvertTo-Bicep template.json` also has this behaviour.

However, this does not seem to be the "powershell" way. Most powershell CmdLets / commands will not overwrite any existing files unless you use the -force flag.

Having ConvertTo-Bicep automatically overwrite files could lead to loss of data for someone who is not aware of this behaviour.

Adding to this, a normal workflow can be creating arm templates using Azure GUI, and saving those as arm, and after this converting to bicep. Since Azure automatically names these exports `template.json` chances of overwriting increases as all these exports will be named `template.bicep`

So: Should we take this in to concideration and follow the standard powershell way, or keep it as it is and follow bicep CLI behaviour?

changing: Is a breaking change but keeps powershell standard

keeping: consistent with Bicep CLI, but can be confusing for powershellers.

**Comment by PalmEmanuel** [comment]
I vote for a breaking change to keep it more PowerShell-y, with a warning if there's a file that wasn't overwritten or vice versa.

**Comment by bjompen** [comment]
the middle road would be the ConfirmPreference way:
If the file already exists ask for permission to overwrite if ConfirmPreference is not set to lower than the command implementation, or run with `-Confirm:$false`.

I honestly don't think that's a good idea, but for the sake of discussion I'm throwing it in here.

**Comment by StefanIvemo** [comment]
After some thinking I've come to the conclusion that I agree. We should stop overwriting the file unless the `-Force` switch is used. `Build-Bicep` also overwrites the file, but that is a completely different story.

**Comment by bjompen** [comment]
Good! Since this is considered breaking though, it should be a major update to the module. Put it on a future feature list, or shall I implement it= How do you want to move ahead with it?

**Comment by StefanIvemo** [comment]
We will go for 2.0 when and if we can solve #182. Maybe we should ship this in 2.0 as well.
