### ISSUE TITLE
Additional functionality to Build-Bicep -GenerateParameterFile

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#25]
**Is your feature request related to a problem? Please describe.**
The `-GenerateParameterFile` switch generates a parameter file with all parameters in the `.bicep` file.  You should be able to specify what type of parameters should be added to the parameter file.

**Describe the solution you'd like**
`-GenerateParameterFile` should be a parameter supporting the following scenarios.

`-GenerateParameterFile All` - Should generate a parameter file with all parameters from template (Parameters with expressions should have expression as value)

`-GenerateParameterFile Required` - Should generate a parameter file with required parameters only

`-GenerateParameterFile Default` - Should generate a parameter file with all parameters that does not have an expression as default value

**Additional context**

**Comment by PalmEmanuel** [comment]
Should be connected to the functionality built in #28

**Comment by alex-frankel** [comment]
Can we also have functionality to *only* generate parameters, without transpiling the bicep code into the ARM template? Now that bicep works natively with PS and Az CLI, I want to build the parameters file from a bicep file and use that in my command as follows:

```powershell
Generate-BicepParameters
az deployment sub create -f main.bicep -p main.parameters.json -l eastus -c
```

**Comment by StefanIvemo** [comment]
@alex-frankel I will fix that, it's a great idea. Plan to ship a new release any day now and we already have the code for such a function from an earlier attempt to improve parameter files.
