### ISSUE TITLE
Update Install-BicepCLI to use the Windows Installer instead of PowerShell

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#27]
**Is your feature request related to a problem? Please describe.**
`Install-BicepCLI` is installed using PowerShell by downloading `bicep.exe` from the latest release. 

**Describe the solution you'd like**
The Windows Installer provided in the official Bicep repository is now signed and should be used instead. This will also simplify the `Uninstall-BicepCLI` command since it doesn't need to look in two different paths. 

**Additional context**
https://github.com/Azure/bicep/issues/1209

**Comment by bjompen** [comment]
Removing the powershell version in Uninstall-BicepCLI could be considered breaking change.
1. Should we really do both these changes in one big bang branch?
2. for compatibility, should we keep the Powershell way in Uninstall-BicepCLI

**Comment by StefanIvemo** [comment]
We should probably start by changing Install-BicepCLI command to use the windows installer. Maybe we can add a switch to Uninstall-BicepCLI where you can choose which type to uninstall. @SimonWahlin had an issue today where a version of the CLI installed with the installer was causing issues.

**Comment by StefanIvemo** [comment]
And maybe create a function that checks if you have it installed in multiple paths.

**Comment by StefanIvemo** [comment]
If you run Update-BicepCLI. It should check if you have multiple installed versions. Remove the one installed with PS. And update by using the windows installer.

**Comment by SimonWahlin** [comment]
My issue was that I had installed bicep version 0.2.212 using the installer. Running Install-BicepCLI properly downloaded version 0.2.328 to `%USERPROFILE%\.bicep`, but the old version were still left in `%USERPROFILE%\AppData\Local\Programs\Bicep CLI` so when I ran `bicep --version` (or Get-BicepVersion) it ran the 0.2.212-binary from AppData.

Running `Uninstall-BicepCLI -Force` before running Install-BicepCLI would probably solved my situation. Maybe `Install-BicepCLI -Force` should do uninstall then install using setup?

Regarding changing Unstall-BicepCLI, I think it is good to keep both paths and uninstaller regardless of where it was installed.

**Comment by bjompen** [comment]
The loading from multiple path problem is hard to solve.. Windows has some kind of search order, so if you have more than one installed it will run whichever is first.

The best solution I think is like Simon says, run `Uninstal-BicepCLI` before *either* if `-Force` is set *or* we implement a `-CleanInstall` switch (or some other  good name)
