### ISSUE TITLE
Implement commands to create parameter files using Bicep syntax

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#28]
**Is your feature request related to a problem? Please describe.**
We should implement commands to enable writing parameter files using Bicep syntax.

>NOTE: This is not an official way of working with parameter files for Bicep. This is a workaround while waiting for native support for parameter files for Bicep. 

**Describe the solution you'd like**
A bicep "parameter file" should be created by authoring a `.bicep` file containing variables only. 

**Example parameter file:**
```
var vnetName = 'westeurope-hub-vnet'
var publicIPCount = 4
var customRoutes= [
  {
    name: 'To-Internet'
    properties: {
      addressPrefix: '0.0.0.0/0'
      nextHopType: 'None'
    }
  }
]
```

We should have two cmdlets supporting parameter files.

**Build-BicepParameterFile**
Should compile a `.bicep` file with variables only to a ARM Template Parameter file format in JSON.

`Build-BicepParameterFile -ParameterFile "./vnet.parameters.bicep"`

This should generate a ARM Template parameter file that looks like this:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vnetName": {
      "value": "westeurope-hub-vnet"
    },
    "publicIPCount ": {
      "value": 4
    },
    "customRoutes": {
      "value": [
        {
          "name": "To-Internet",
          "properties": {
            "addressPrefix": "0.0.0.0/0",
            "nextHopType": "None"
          }
        }
      ]
    }
  }
}
```

**New-BicepParameterFile**
We should also be able to generate a parameter file in `.bicep` format by referring to a `.bicep` file.

You have a bicep template that looks like this. 
Example:
**nsg.bicep**
```
param name string = 'nsg1'
param securityRules array = []
param tags object = {}
param location string = resourceGroup().location

resource nsg  'Microsoft.Network/networkSecurityGroups@2020-06-01' = {
    name: name
    location: location
    properties: {
        securityRules: securityRules
    }    
}
```
You should then be able to create a `.bicep` format paramter file by running the following cmdlet.

`New-BicepParameterFile -TemplateFile "./nsg.bicep"`

This should generate a parameter file that looks like this. 

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "name": {
      "value": "nsg1"
    },
    "securityRules ": {
      "value": []
    },
    "tags ": {
      "value": {}
    },
    "location":{
      "value": ""
    }
  }
}
```

**Additional context**
This will most likely be replaced with core Bicep functionality once Bicep natively supports parameter files.

**Comment by PalmEmanuel** [comment]
@StefanIvemo Regarding `Build-BicepParameterFile` - Do we want the same result as what the CLI outputs?

Example from my local `bicep build`:
```
var vnetName = 'westeurope-hub-vnet'
var publicIPCount = 4
var customRoutes= [
  {
    name: 'To-Internet'
    properties: {
      addressPrefix: '0.0.0.0/0'
      nextHopType: 'None'
    }
  }
]
```
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "functions": [],
  "variables": {
    "vnetName": "westeurope-hub-vnet",
    "publicIPCount": 4,
    "customRoutes": [
      {
        "name": "To-Internet",
        "properties": {
          "addressPrefix": "0.0.0.0/0",
          "nextHopType": "None"
        }
      }
    ]
  },
  "resources": []
}
```

**Comment by StefanIvemo** [comment]
@PalmEmanuel for it to be a valid ARM Template parameter file we need to have the `"value"` property.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/parameter-files

**Comment by StefanIvemo** [comment]
To confusing for users, lets wait for real Bicep parameter files
