### ISSUE TITLE
Add -Nightly switch to Install-BicepCLI

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#52]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to run the Bicep CLI nightly build.

**Describe the solution you'd like**
I would like to see a `Install-BicepCLI -Nightly` switch to fetch and install Bicep CLI using nightly build. 

**Additional context**

**Comment by PalmEmanuel** [comment]
The GitHub actions feature of the Bicep repository is locked behind authorization, meaning we can't download the artifacts from the nightly build unless we authenticate with a GitHub account. We'll need to investigate whether or not there is a good solution for this.

**Comment by StefanIvemo** [comment]
I'm not sure for how long it will be interesting to run nightly builds. Maybe we should park this one.

**Comment by StefanIvemo** [comment]
Closing this since there is no good way to retrieve the artifacts needed unauthenticated.
