### ISSUE TITLE
Create Bicep PowerShell logo

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#53]
You know what to do @bjompen. Work your magic.

**Comment by bjompen** [comment]
Adjusted colours to match "PowerShell blue", reversed and skewed the arm to the > symbol, and added the underline.

Opinions?

![image](https://user-images.githubusercontent.com/17783007/107982026-94c24e80-6fc3-11eb-9753-317ca1d67b66.png)

**Comment by StefanIvemo** [comment]
Sweet!

**Comment by bjompen** [comment]
new suggestion.

**Comment by StefanIvemo** [comment]
Like the second one better. Will it look completely off to move the arm a little bit to the left to provide some space between the arm and underline?

**Comment by bjompen** [comment]
Good point! It honestly looks even better I think.
![image](https://user-images.githubusercontent.com/17783007/108071577-2edad300-7066-11eb-858f-abb1d80339c6.png)

**Comment by StefanIvemo** [comment]
Love it!
