### ISSUE TITLE
Update-BicepCLI and Install-BicepCLI should uninstall Bicep CLI installed to %userprofile%\.bicep

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#59]
**Describe the bug**
If a user have installed Bicep CLI using the PowerShell script provided by the Bicep team or using our previous versions of the module, a `bicep.exe` will remain in the `%userprofile%\.bicep`. This will result in a conflict where the old version of Bicep CLI will be used over any version installed by the windows installer `Update-BicepCLI` and `Install-BicepCLI`.

**To Reproduce**
Install older version of Bicep CLI using PowerShell Script. Then install Bicep CLI using `Install-BicepCLI`.

**Expected behavior**
`Install-BicepCLI` and `Update-BicepCLI` should verify if there is a version installed to `%userprofile%\.bicep`, and if so delete it.

**Additional context**

**Comment by bjompen** [comment]
related discussion: #27

**Comment by bjompen** [comment]
I partly agree with this. Update-BicepCLI should always check
- Is Bicep installed
- Which version is installed
- if version is old, uninstall and install newest one

```PowerShell
Get-Verb Update

Verb   AliasPrefix Group Description
----   ----------- ----- -----------
Update ud          Data  Brings a resource up-to-date to maintain its state, accuracy, conformance, or compliance
```

However, Install-BicepCLI should not run uninstall or remove any settings. This would be contradisctional to what the verb of the CmdLet states. 
```powershell
Get-Verb Install

Verb    AliasPrefix Group     Description
----    ----------- -----     -----------
Install is          Lifecycle Places a resource in a location, and optionally initializes it
```

Like said in previous discussion: We could add a "-Clean" or similar switch to install to make it destructive, but I think even this is counter intuitive as it would just replicate the behaviour of update in that case.

**Comment by StefanIvemo** [comment]
Agreed @bjompen. Let's keep `Install-BicepCLI` as is. Maybe we could add a warning message though. 
`WARNING: you are running multiple installations of Bicep CLI, correct it using....`
