### ISSUE TITLE
Create Update-BicepTypes cmdlet

### ISSUE THREAD

**Issue by StefanIvemo** [StefanIvemo/BicepPowerShell#66]
**Is your feature request related to a problem? Please describe.**
With the implementation of `Get-BicepApiReference` we need a way for users to update the BicepTypes.json file.

**Describe the solution you'd like**
Implement a cmdlet named something like `Update-BicepTypes` to download the latest type info.

**Additional context**

**Comment by JohnRoos** [comment]
Depending on #64
