### ISSUE TITLE
Suppress warning messages of specific code when running Build-Bicep

### ISSUE THREAD

**Issue by SimonWahlin** [StefanIvemo/BicepPowerShell#67]
**Is your feature request related to a problem? Please describe.**
When running Build-Bicep I always get a lot of Warning BCP081: Resource type "..." does not have types available.

Once I've made sure they are reported as missing, I don't want to see these warnings any more since they make it hard to see any other warning that I might care about.

**Describe the solution you'd like**
I would like to have a configurable list of warnings that will be suppressed, either by Code or even better, by code and message.

I'm thinking a cmdlet like `Add/Set/Get/Remove-BicepOption -SupressWarning 'BCP081'`

The parameter SupressWarning would accept a string or a hashatble like this:
```
Add-BicepOption -SupressWarning @{
    Code='BCP81'
    Message = 'Resource type "Microsoft.Network/networkSecurityGroups@2020-08-01" does not have types available.'
}
```

These settings can be stored in a module-scoped variable and I can add them to my profile.ps1 to persist them between sessions, or maybe even be persisted to a file in my user profile?

**Comment by StefanIvemo** [comment]
I like it! I think we should add a message to the build output that informs me that I have suppressed warnings. 

```
**WARNING: Suppressing 4 build warnings, to view configured exceptions use `Get-BicepOption`.**
C:\git\Azure\bicep\docs\examples\301\modules-vwan-to-vnet-s2s-with-fw\azfwpip.bicep(34,11) : Error BCP004: The string at this location is not terminated due to an unexpected new line character.
C:\git\Azure\bicep\docs\examples\301\modules-vwan-to-vnet-s2s-with-fw\azfwpip.bicep(44,20) : Error BCP026: The output expects a value of type "object" but the provided value is of type "string".
Write-Error: 
Line |
  44 |                      $ARMTemplate = ParseBicep -Path $file.FullName
     |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Buildning file C:\git\Azure\bicep\docs\examples\301\modules-vwan-to-vnet-s2s-with-fw\azfwpip.bicep returned with errors. See Information stream for details 
```

**Comment by StefanIvemo** [comment]
Should we close this?

**Comment by SimonWahlin** [comment]
Yea we can close this now.
