### ISSUE TITLE
The script downloadAssemblies.ps1 also downloads non-assembly JSON file

### ISSUE THREAD

**Issue by PalmEmanuel** [StefanIvemo/BicepPowerShell#90]
I suggest a renaming of the file for clarity.

**Comment by bjompen** [comment]
Agree. 

We should also handle trying to import the module without the assemblies more graceful. 

Today if we try to import the module from a cloned repo before running downloadAssemblies we get an error message like `Can't find bicepTypes.json`.

This error should instead say something like 
```text
If you are trying to import this module from a cloned repo, please do xyz.
If you are getting this error and have installed using the PowerShell gallery, please report a bug
```
