### ISSUE TITLE
Get-BicepApiReference opens wrong url when no parameters are provided

### ISSUE THREAD

**Issue by JohnRoos** [StefanIvemo/BicepPowerShell#94]
**Describe the bug**
Get-BicepApiReference has a default parameter set without any mandatory parameters. When running the command without any parameters you will be redirected to this url: https://docs.microsoft.com/en-us/azure/templates///

**To Reproduce**
1. Get-BicepApiReference
2. Check the Url on the opened browser window

**Expected behavior**
Two alternatives.
1. The command throws an error because a mandatory parameter is missing (Type)
2. The command opens the reference start page without extra trailing slashes: https://docs.microsoft.com/en-us/azure/templates/

**Comment by bjompen** [comment]
Alt. 2 makes much more sense, plus adds the feature "let me browse".
